# 配置项，勿删！
^Dict>.*: |
  >>>f
  local str=string.sub(msg.fromMsg,#"Dict>"+1)
  local json = require('json')

  if str == "list" then

    return "词典列表:\n"..list

  elseif str == "config" then

    local function table_map(t,fn)
      for k,v in pairs(t) do
        t[k] = fn(v,k)
      end
    end
    local tbl = settings
    local str = ""

      table_map(tbl,function(v,k)
        return tostring(v)
      end)
      
      for k,v in pairs(tbl) do
        str = str..k.."="..v.."\n"
      end

      return str
  end
